### ISSUE TITLE
Potential replay attack on updates

### ISSUE THREAD

**Issue by matiassequeira** [janjongboom/lorawan-fota-signing-tool#4]
Hi! I've been studying your FUOTA mechanism from the security perspective and first of all thanks for the hard work!

For what I understood, what's sent to the device is the binary update (full binary or diff) plus a manifest, and the manifest contains:

- Signature length + Signature
- manufacturerUUID, deviceClassUUID, 
- versionBuffer: derived from a timestamp
- isDiffBuffer: seems to be a bool

Since the `versionBuffer` field in the manifest is not signed, it makes the FUOTA mechanism susceptible to replay attacks. This is, an attacker that previously sniffed a FUOTA is able to replay it, which can lead into a software downgrade. 

Maybe the simplest approach to get around this problem is to use incremental versions and sign the version field as well? Let me know your thoughts, thanks.

**Comment by janjongboom** [comment]
Hi @matiassequeira, I've moved on from Arm since writing this part, so I won't be addressing this in this repository - the idea was always to move to https://tools.ietf.org/id/draft-moran-fud-manifest-00.html or something similar from that WG, so this was a stopgap. Anyway, a quick check on the application side to disallow downgrades would work as well, I can't remember if we implemented that on the reference application though.
